services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: node1
    networks:
      - seupet-net

  node2:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: node2
    networks:
      - seupet-net

  node3:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: node3
    networks:
      - seupet-net

  node4:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: node4
    networks:
      - seupet-net

  node5:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: node5
    networks:
      - seupet-net

  loadbalance:
    image: nginx:alpine
    container_name: loadbalance
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
    networks:
      - seupet-net

networks:
  seupet-net:
    driver: bridge
